#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Apr 24 12:29:10 2020

@author: paolucci
"""

import unittest
from mesaPROTON_OC import MesaPROTON_OC
import Person

class TestPROTON(unittest.TestCase):

    # that's strange - at somepoint it always failed the first run after changing something, then no more
    def test_weddings(self):
        m = MesaPROTON_OC()
        print(m.number_weddings)
        m.number_weddings_mean = 1000  
        for i in range(1,5):
            m.wedding()
        #print(Person.NumberOfLinks()-l)
        self.assertEqual(len([x for x in m.schedule.agents if x.partner and x.partner.partner != x]), 0)
        self.assertEqual(m.number_weddings, len([x for x in m.schedule.agents if x.partner]) / 2)
        self.assertTrue(m.number_weddings > 0)
        # coherent state of weddings


if __name__ == '__main__':
    unittest.main()